# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import counter_pb2 as counter__pb2


class LetterCounterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountLetters = channel.unary_unary(
                '/lettercounter.LetterCounter/CountLetters',
                request_serializer=counter__pb2.Text.SerializeToString,
                response_deserializer=counter__pb2.Count.FromString,
                )


class LetterCounterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountLetters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LetterCounterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountLetters': grpc.unary_unary_rpc_method_handler(
                    servicer.CountLetters,
                    request_deserializer=counter__pb2.Text.FromString,
                    response_serializer=counter__pb2.Count.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lettercounter.LetterCounter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LetterCounter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountLetters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lettercounter.LetterCounter/CountLetters',
            counter__pb2.Text.SerializeToString,
            counter__pb2.Count.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
